### ISSUE TITLE
Users should not have to enter a personal access token

### ISSUE THREAD

**Issue by DavidParks8** [jycouet/VSTSExtensions#1]
There is already an option `Allow scripts to access OAuth token` in a build definition. That is the way that other tasks access protected resources (provided the build identity has the proper permissions). It seems unnecessary additional setup to have to generate a custom PAT.

**Comment by jycouet** [comment]
Hi @DavidParks8 
Thanks for the info, I'll have a look.

**Comment by DavidParks8** [comment]
An example of how to use it can be found at https://github.com/Microsoft/vsts-tasks/blob/57cd7604cfea18cd7ca82cb20c6c6921f9785d6e/Tasks/DotNetCoreCLI/restorecommand.ts#L50

**Comment by jycouet** [comment]
Thank you again.
It's fixed with commit: https://github.com/jycouet/VSTSExtensions/commit/9924fdf2e36c97a5321ad873486a465f357f143e
