### ISSUE TITLE
Productionize This Extension

### ISSUE THREAD

**Issue by DavidParks8** [jycouet/VSTSExtensions#12]
I would like for this extension to become productionized so that we can push it for higher visibility and use. My end goal is to be allowed to use it internally at Microsoft. To reach this state, we need a proper readme with extensive documentation, a proper continuous integration setup which includes security scanning, a bunch of guides like how to contribute and general processes, and possibly integration with nuget packages.

**Comment by jycouet** [comment]
Time is flying... already more than a year!!!
I would like to push it more too, and ready to do more, so... where do we start? :)

**Comment by jycouet** [comment]
I close this ticket with https://github.com/jycouet/VSTSExtensions/pull/20.
Please feel free to reopen it if you have other ideas :)
