### ISSUE TITLE
Task does not set result on completion

### ISSUE THREAD

**Issue by DavidParks8** [jycouet/VSTSExtensions#2]
Take a look at https://github.com/Microsoft/vsts-tasks/blob/57cd7604cfea18cd7ca82cb20c6c6921f9785d6e/Tasks/DotNetCoreInstaller/dotnetcoreinstaller.ts#L165

A task should report its status back to the task runner so that a build properly fails or succeeds.

**Comment by jycouet** [comment]
Fixed with commit: https://github.com/jycouet/VSTSExtensions/commit/9924fdf2e36c97a5321ad873486a465f357f143e

Thank you :)
