### ISSUE TITLE
How to exclude specific folders?

### ISSUE THREAD

**Issue by mmodi** [jycouet/VSTSExtensions#22]
#### This is a:

- [ ] Bug report
- [ ] Feature request

**Comment by jycouet** [comment]
Regarding what?

**Comment by mmodi** [comment]
Hi @jycouet  I am using Renovate extension in the VSTS pipeline. Now, I am running the build against one of my branch. In this code base, I am using few static dependencies and I want to exclude static folder while Renovate extension check for the stable release. So, how can I exclude a specific folder?

**Comment by jycouet** [comment]
Hello, 

Can you try in adding the arg: **--copy-local-libs**?
Like this:
![image](https://user-images.githubusercontent.com/5312607/67100870-c6a18600-f1c0-11e9-9587-b0b00217c962.png)

Thank you

**Comment by mmodi** [comment]
Hi @jycouet Thanks for the update. 

Somehow Renovate extension stopped working, I am getting the below error:
![Screenshot from 2019-10-18 17-41-50](https://user-images.githubusercontent.com/1021278/67108404-b690a300-f1ce-11e9-932f-de496d704ec2.png)

After removing the argument also result is the same.
