### ISSUE TITLE
Issue with Renovate Me VSTS Extension

### ISSUE THREAD

**Issue by mmodi** [jycouet/VSTSExtensions#23]
#### This is a:

- [x] Bug report
An extension was working fine till last Thursday. Somehow from Friday onwards, I am getting below issue. I tried by removing the extension and added it again. Also changed the Node version but the issue still persists. 
Here is my configuration: renovate.json
{
    "extends": [
        "config:base"
    ],
    "ignorePaths": [
        "**/client/**",
        "**/jsdoc/**",
        "**/node_modules/**"
    ],
    "enabledManagers": [
        "npm"
    ]
}

- [ ] Feature request

#### Description
ERROR: Repository has unknown error (repository=femina/femina)
       "err": {
         "message": "Cannot convert undefined or null to object",
         "stack": "TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at Object.getMergeMethod (C:\\npm\\cache\\_npx\\584\\node_modules\\renovate\\dist\\platform\\azure\\azure-helper.js:212:20)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
       }
 INFO: Finished repository (repository=femina/femina)
 INFO: Renovate finished
 INFO: Renovate is exiting with a non-zero code due to the following logged errors
       "loggerErrors": [
         {
           "name": "renovate",
           "level": 50,
           "repository": "femina/femina",
           "err": {
             "message": "Cannot convert undefined or null to object",
             "stack": "TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at Object.getMergeMethod (C:\\npm\\cache\\_npx\\584\\node_modules\\renovate\\dist\\platform\\azure\\azure-helper.js:212:20)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
           },
           "msg": "Repository has unknown error"
         }
       ]
fs.js:114
    throw err;
    ^

Error: EPERM: operation not permitted, unlink 'C:\npm\cache\_npx\584\node_modules\renovate\node_modules\re2\build\Release\re2.node'
    at Object.unlinkSync (fs.js:956:3)
    at fixWinEPERMSync (C:\hostedtoolcache\windows\node\10.16.3\x64\node_modules\npm\node_modules\rimraf\rimraf.js:211:13)
    at rimrafSync (C:\hostedtoolcache\windows\node\10.16.3\x64\node_modules\npm\node_modules\rimraf\rimraf.js:311:28)
    at C:\hostedtoolcache\windows\node\10.16.3\x64\node_modules\npm\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\hostedtoolcache\windows\node\10.16.3\x64\node_modules\npm\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\hostedtoolcache\windows\node\10.16.3\x64\node_modules\npm\node_modules\rimraf\rimraf.js:334:7)
    at fixWinEPERMSync (C:\hostedtoolcache\windows\node\10.16.3\x64\node_modules\npm\node_modules\rimraf\rimraf.js:209:5)
    at rimrafSync (C:\hostedtoolcache\windows\node\10.16.3\x64\node_modules\npm\node_modules\rimraf\rimraf.js:311:28)
    at C:\hostedtoolcache\windows\node\10.16.3\x64\node_modules\npm\node_modules\rimraf\rimraf.js:342:5

**Comment by jycouet** [comment]
Could you check with an older version of renovate? 
Here you can find the list of versions: https://www.npmjs.com/package/renovate
Replace latest by `19.61.5` for example to see.

On what Agent are you running this build? Your own one? A DevOps one? Windows? Linux?

**Comment by mmodi** [comment]
Thanks, it's working with 19.61.5.

**Comment by jycouet** [comment]
That mean that there is an issue with the latest Renovate. Can you test again and confirm?
Could you give me your OS as info? 

Thx a lot 👍

**Comment by mmodi** [comment]
Yes, issue with the latest version. I tried in all the versions starting from 19.62.0 and same error is there. I am using Renovate extension within the VSTS build pipeline having Ubuntu 18.04. I tried in Ubuntu 16.04 too but the same error is there.
