### ISSUE TITLE
`result` is redundant and can be removed

### ISSUE THREAD

**Issue by DavidParks8** [jycouet/VSTSExtensions#3]
No matter what occurs, `result` is set to `1`. Additionally, it is never used outside of the `exec` function, so it is not necessary. https://github.com/jycouet/VSTSExtensions/blob/a9c523d590713a96d540f66792429e52a2fdb63b/renovateMe/buildtask/src/index.ts#L42

**Comment by jycouet** [comment]
Fixed with commit: https://github.com/jycouet/VSTSExtensions/commit/9924fdf2e36c97a5321ad873486a465f357f143e

I think it's better like this
