### ISSUE TITLE
Support Azure DevOps Git Builds  

### ISSUE THREAD

**Issue by p0onage** [jycouet/VSTSExtensions#35]
Is Azure DevOps not supported?

I'm getting this error message

`##[error]Error: Sorry, we support only TfsGit for now. Please post an issue if you need more :)`

My repository is hosted in GitHub and the build is on Azure Devops. I also have a scenario for Azure Repo and Azure Devop Build too should this work?

My build pipeline is here 
https://github.com/p0onage/RenovateBot

**Comment by jycouet** [comment]
With azure repo & devops build, this will work.

If you want to renovate your github repo, you should go directly with https://github.com/renovatebot/renovate IMO.

I let you close the ticket if you agree 👍

**Comment by p0onage** [comment]
Thanks @jycouet I'll give that a try
