### ISSUE TITLE
[renovateme] allow passing config.js / config.json

### ISSUE THREAD

**Issue by viceice** [jycouet/VSTSExtensions#36]
**Is your feature request related to a problem? Please describe.**
I would like to pass a `config.js` / `config.json` to renovate current exection directory, so it can read it.

**Describe the solution you'd like**
Sometimes it's hard to write hostRules as commandline args for renovate, because they need to be an json array.
By default renovate will load a `config.js` or `config.json` from current directory ( `$PWD` ), the file can be overridden by `RENOVATE_CONFIG_FILE` env.

**Describe alternatives you've considered**
encode all params  to cli args

**Additional context**

**Comment by jycouet** [comment]
Sorry, I didn't want to overparametrize this small extension.
If you use a `.yaml` file for your CI, args are already versioned and everything no? 

Will it be a real improvement?
can't you simply set `RENOVATE_CONFIG_FILE` path only?

**Comment by viceice** [comment]
I don't now azure pipelines well.

We have a renovate user who has trouble passing the required parameters to renovate. So i thought is would be nice to pass the `config.js` to renovate. If your extension is running renovate in the repo root dir, an we put a config.js there, it should work out of the box. What dou you think? Is there any other security layer between?

**Comment by jycouet** [comment]
Yes, it should work out of the box with the file on the root dir 👍

**Comment by viceice** [comment]
Can you add a docu hint for the `config.js`? so new users know about setting. Also a link to https://docs.renovatebot.com/self-hosted-configuration/ for possible options should help.

**Comment by jycouet** [comment]
Could be a good idea 👍
Would you do a PR with your proposal? (I can't do it right now)

**Comment by viceice** [comment]
maybe later yes, currently very busy 🙃

**Comment by jycouet** [comment]
https://github.com/jycouet/VSTSExtensions/commit/89df95c0e8c96697c61f05557899ae2bd4cc1a6a
