### ISSUE TITLE
How to verify a specific project

### ISSUE THREAD

**Issue by p13t3rict** [jycouet/VSTSExtensions#38]
I have multiple projects in the same repository. I understood from [this related issue](https://github.com/jycouet/VSTSExtensions/issues/33) that RenovateMe only checks one project by design. How can I configure RenovateMe to verify a specific project? 

I would like to do this so I can add the RenovateMe task multiple times so that all projects are checked.

**Comment by jycouet** [comment]
The best is to set up multiple CI, one per Repo.
I would suggest having the CI config in a yaml file so that it will be reused all the time.

Hope it's solving your point
