### ISSUE TITLE
Renovate Me PRs Autocompletion not working in Azure Devops

### ISSUE THREAD

**Issue by salahBouragba** [jycouet/VSTSExtensions#50]
**Describe the bug**
The PRs created by the Renovate Me task are not automatically merged even when automerge is set to true

**To Reproduce**
1. Configure renovate with the following params ("automerge": true, "automergeType": "pr", "platformAutomerge": true, "automergeStrategy": "squash")
2. Modify the main branch policy to only allow "Squash merge" type
3. Create a new CI pipeline in azure devops with Renovate Me task
4. Go to the generated PR
5. See that it's not automatically completed

**Expected behavior**
The PR should be complete

**Screenshots**
![151967581-e54b80e8-c9a5-4db8-8b0e-5b835f7ea184](https://user-images.githubusercontent.com/98818340/152181598-c9a4604a-7afc-4c73-82d1-0da8a2ca5708.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Edge + Chrome + Firefox
 - Version: latest versions (Edge 97.0.1072.76, Chrome:  97.0.4692.99, Firefox: 96.0.1)

**Comment by jycouet** [comment]
I never used this, but with the screenshot it seems that everything is "well done".
What does the orange icon mean?

**Comment by salahBouragba** [comment]
It's the Azure Devops feature that marks the PR as autoComplete so when all policies are good, the PR will be automatically merged

**Comment by jycouet** [comment]
As you say, it's a "Azure Devops feature... PR will be automatically merged".
So what Renovate Me can do for that?

**Comment by Sayali1638** [comment]
I am trying to run whitesource renovate using azure pipeline. I have followed [this](https://marketplace.visualstudio.com/items?itemName=jyc.vsts-extensions-renovate-me) documentation.
My pipeline looks as follows:
![image](https://user-images.githubusercontent.com/66510021/157239212-fb772a24-8d12-4044-a0fd-5a02bba4b633.png)

I have added the linux agent for the agent pool. When I try running the pipeline I face following error:
##[error]self signed certificate in certificate chain

I have tried running it as mentioned but it is not working for me.

Please let me know how do I resolve the error. I am also not sure of where do I place the key provided by renovate.

**Comment by Sayali1638** [comment]
Hello,

The certificate error is resolved but not sure why I am getting following error:
##[error]exec(npx, renovate@latest "ExtenSURE"/"EagleView" --platform azure --endpoint http://azuredevops.co.in/FB_Collection1/ --token *** ): Error: The process '/home/sayali_bhase/agent/_work/_tool/node/8.8.0/x64/bin/npx' failed with exit code 1
##[error]Error: exec(npx, renovate@latest "ExtenSURE"/"EagleView" --platform azure --endpoint http://azuredevops.co.in/FB_Collection1/ --token *** ): Error: The process '/home/sayali_bhase/agent/_work/_tool/node/8.8.0/x64/bin/npx' failed with exit code 1
Finishing: Renovate

I also checked it on internet but did not find any solution. 
Please let me know.

**Comment by sheldonhull** [comment]
I got this to work. It was a little tricky but not renovates fault here I think.

So first off, if you have a review policy it can impact these things, and I recommend to protect with a review policy for the various paths/code you have so it can't merge without approval of the right folks. 

This combination works for me, but I'm not saying all of it is required. 

```json
 "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "dependencyDashboard": true,
  "dependencyDashboardAutoclose": true,
  "platformAutomerge": true,
  "azureWorkItemId": workitemid, // just create a bug and link work automatically to this to fufill the requirements of policies,
  "automerge": true,
  "automergeStrategy": "squash",
  "semanticCommitType": "chore",
  "semanticCommitScope": "deps",
  "rebaseWhen": "behind-base-branch",
  "prCreation": "not-pending",
  "pruneStaleBranches": true,
  "unicodeEmoji": true,
  "stabilityDays": 5,
```

Something like that with other various settings worked out great and I get PR's generated with dependencies and all like clockwork. I love this extension so thank you!
