### ISSUE TITLE
RenovateMe.yaml broken link

### ISSUE THREAD

**Issue by smugleafdev** [jycouet/VSTSExtensions#52]
On the [main page](https://marketplace.visualstudio.com/items?itemName=jyc.vsts-extensions-renovate-me) where it says:

> Find an example here: [RenovateMe.yaml](https://marketplace.visualstudio.com/RenovateMe.yaml)

The link is broken and goes to a 404.

I can find it myself [here](https://github.com/jycouet/VSTSExtensions/blob/master/renovateMe/RenovateMe.yaml) in GitHub, but still.

**Comment by jycouet** [comment]
e6b0807ae5c8342f5f7e94daf0bd85ac7be04637
