### ISSUE TITLE
Renovate Me always runs on the default branch instead of the one selected in the pipeline

### ISSUE THREAD

**Issue by DirkvanWijk** [jycouet/VSTSExtensions#53]
**Describe the bug**
When I start the Azure pipeline with the Renovate Me task, it does not take into consideration which branch I have selected in the pipeline run. It will always run renovate on the branch that is selected as default in Azure Devops.

**To Reproduce**
1. Start the renovate pipeline and select a branch different than your default branch.
2. Renovate will ignore the argument and run on the default branch instead.

**Expected behavior**
I am expecting that it will run Renovate on the branch that is selected in the pipeline run.

In this screen, when I select to run on develop, it will instead run on master, as this is the default branch.

![image](https://user-images.githubusercontent.com/19604403/156591210-1ba4f72a-79da-44cf-b878-1bfe61bd9c22.png)

**Comment by jycouet** [comment]
I would not say that it's a bug as it was intended to work against the default branch.
As I'm not working much on VSTS anymore I can't really improve this behavior.

Of course, you can PR the repo to add this feature. I'll merge and publish👍

**Comment by DirkvanWijk** [comment]
I already had a hunch this was intended behavior. Too bad it won't be addressed. 

Since I have no experience in this area whatsoever, I doubt I will fix it myself 😅
