### ISSUE TITLE
Error self signed certificate

### ISSUE THREAD

**Issue by jycouet** [jycouet/VSTSExtensions#54]
I am trying to run whitesource renovate using azure pipeline. I have followed [this](https://marketplace.visualstudio.com/items?itemName=jyc.vsts-extensions-renovate-me) documentation.
My pipeline looks as follows:
![image](https://user-images.githubusercontent.com/66510021/157239212-fb772a24-8d12-4044-a0fd-5a02bba4b633.png)

I have added the linux agent for the agent pool. When I try running the pipeline I face following error:
##[error]self signed certificate in certificate chain

I have tried running it as mentioned but it is not working for me.

Please let me know how do I resolve the error. I am also not sure of where do I place the key provided by renovate.

_Originally posted by @Sayali1638 in https://github.com/jycouet/VSTSExtensions/issues/50#issuecomment-1061732851_

**Comment by jycouet** [comment]
Did you add this?

![image](https://user-images.githubusercontent.com/5312607/157239937-f8f9676e-3a2a-43ce-833a-8a7496d3ad27.png)

**Comment by Sayali1638** [comment]
Hello,
I have enabled the options mentioned above for the repository
<img width="482" alt="image" src="https://user-images.githubusercontent.com/66510021/157644231-503010af-e44a-44cb-9f9e-0f45ad1f0bc4.png">


I am still getting the same error.
Please let me know if I am missing on something

**Comment by jycouet** [comment]
I assumed that you had found your way.
I'll close it, please re open if needed
