### ISSUE TITLE
Renovate Me: support for multiple repos

### ISSUE THREAD

**Issue by dapathy** [jycouet/VSTSExtensions#56]
**Is your feature request related to a problem? Please describe.**
Renovate Me extension appears to always use the current repo ignoring repos defined in config

**Describe the solution you'd like**
An option to not use current repo and fallback to list in config.js
I _think_ we just need to not include the project and repo in the args. Perhaps a new input could toggle that behavior.

https://docs.renovatebot.com/modules/platform/azure/#using-a-single-pipeline-to-update-multiple-repositories

**Comment by jycouet** [comment]
Hello, 
Thank you for your feedback. The goal of Renovate **ME** is only to renovate **ME**, the current repo.

You would also need a token that is available for all repos (the scope is different).

I think that in your case, you should use renovate directly and not the easy setup of Renovate Me.
Actually, You would like RenovateAll and not Me (and that's renovate 😉)

**Comment by dapathy** [comment]
Thank you for the explanation :)
