### ISSUE TITLE
Renovate Me on Azure Dev Ops

### ISSUE THREAD

**Issue by Marvinnnne** [jycouet/VSTSExtensions#57]
I want to run Renovate Me on Azure Dev Ops. I used Azure Dev Ops Ubuntu Agent.

I have follow the minimal requirement but I have this error.
![Error_RenovateMe](https://user-images.githubusercontent.com/9744563/200534820-04e363f2-7d7c-4bb2-b58d-51e75ca10159.png)

Here my pipeline :
![Pipeline_RenovateMe](https://user-images.githubusercontent.com/9744563/200534792-13fbe02a-967f-4979-8e18-383525c149a0.png)

In the setup, the Github token is optional.

**Comment by jycouet** [comment]
Strange!

Could you try with a new version of node?

**Comment by Marvinnnne** [comment]
I notice this error : 
"stack": "Error: Pushing to [https://urcapgemini.visualstudio.com/UR-crm/_git/UR-crm\nremote](https://urcapgemini.visualstudio.com/UR-crm/_git/UR-crm/nremote): 001f# service=git-receive-pack\nremote: 0000000000aaTF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\\4db0e25f-1fc9-47b8-919f-a64f6cee9cf1', scope 'repository'.\nremote: TF401027: You need the Git 'GenericContribute' permission to perform this action. Details: identity 'Build\\4db0e25f-1fc9-47b8-919f-a64f6cee9cf1', scope 'repository'.\nfatal: unable to access 'https://urcapgemini.visualstudio.com/UR-crm/_git/UR-crm/': The requested URL returned error: 403\n\n    at Object.action (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/simple-git/dist/cjs/index.js:1228:25)\n    at PluginStore.exec (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/simple-git/dist/cjs/index.js:1263:29)\n    at /home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/simple-git/dist/cjs/index.js:1627:43\n    at new Promise (<anonymous>)\n    at GitExecutorChain.handleTaskData (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/simple-git/dist/cjs/index.js:1625:16)\n    at GitExecutorChain.<anonymous> (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/simple-git/dist/cjs/index.js:1609:44)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/simple-git/dist/cjs/index.js:55:24)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"

But my user have the good right 
![Right_RenovateMe](https://user-images.githubusercontent.com/9744563/200573720-7377c4cb-6f5d-4cd4-9da7-b90bea44a721.png)

**Comment by Marvinnnne** [comment]
It works. I didn't use a good user. Thanks for your help
