### ISSUE TITLE
Extension Renovate Me still in preview

### ISSUE THREAD

**Issue by SebastianSchuetze** [jycouet/VSTSExtensions#59]
**Is your feature request related to a problem? Please describe.**
The Extension could help to simplify usage of 'Renovate Me'. But I am working in a Plattform team at Deutsche Bahn, and we would like to provide the extension to roughly 3000 users on our many AzDO organizations. But for Enterprises like Deutsche Bahn there is one rule that we do not install / allow preview services within the company.

You extension has been out for years. Is the version 1.0 just a matter of version / confidence or is it still preview?
How could we help to get it into "production"?

**Describe the solution you'd like**
Make it officially non preview version 1.0

**Describe alternatives you've considered**
use renovate me with another custom extension or just scripts

**Comment by SebastianSchuetze** [comment]
@jycouet maybe I can push this a bit. And merry christmas! :)

**Comment by jycouet** [comment]
Thx for reaching out 🎉

I was in a big company before, and we had such rules as well. Now it make me laugh a bit 😅

Yes, I could bump it 👌

**Comment by jycouet** [comment]
Should be live: https://marketplace.visualstudio.com/items?itemName=jyc.vsts-extensions-renovate-me in version `1.0.1`
Let me know 🥳

**Comment by SebastianSchuetze** [comment]
Thanks @jycouet but one important thing was the preview flag in the. Created the PR #61 for this. :)

**Comment by jycouet** [comment]
`1.0.2` just got published 🎉 
Thx a lot @SebastianSchuetze 

(Is it better, I don't see the preview tag in https://marketplace.visualstudio.com/items?itemName=jyc.vsts-extensions-renovate-me)
I let you close the ticket if it's good 👍

**Comment by SebastianSchuetze** [comment]
All good now!
