### ISSUE TITLE
Not all builds use git as source control

### ISSUE THREAD

**Issue by DavidParks8** [jycouet/VSTSExtensions#6]
This is a possible edge case, and should probably cause the task to fail.

**Comment by jycouet** [comment]
Yes you are probably right.
We should probably:
1) warn people in readme
1) check it at the begining of the script

**Comment by jycouet** [comment]
Hope done!
1) readme:  https://github.com/jycouet/VSTSExtensions/commit/f1d44c4e79f8677010cf4844e657c54f0ea2fb9f
2) in index.ts:  https://github.com/jycouet/VSTSExtensions/commit/d37ff9535ad4f6ec087405380f8fb2464a298032

**Comment by DavidParks8** [comment]
Whoops, you beat me to it.

**Comment by jycouet** [comment]
haha :) sorry
I'm too hyped on my first open source repo :D
