### ISSUE TITLE
Update renovate extension to support node version 6

### ISSUE THREAD

**Issue by SebastianSchuetze** [jycouet/VSTSExtensions#68]
**Describe the bug**
You task in the task.json in the execution property is only supporting node 6 by using "Node". You should only support "Node10" or "Node16".

**To Reproduce**
Run a pipeline with an agent which does not support node 6

**Expected behavior**
support node 10 or 16

**Additional context**
Microsoft is depricating node 6 and should support node 16 or at least node 10

**Comment by jycouet** [comment]
🙏 thx
https://github.com/jycouet/VSTSExtensions/pull/69

I'll try to upload it now

**Comment by ttothea** [comment]
hej, thanks for reaching out!. I'm a bit tied up at the moment and won't be able to test the code right now. I will keep this in my mind and will do my best to circle back at it later. Appreciate your understanding!
