### ISSUE TITLE
Invalid renovate.json does not fail the Azure DevOps pipeline

### ISSUE THREAD

**Issue by KaVeKa** [jycouet/VSTSExtensions#70]
**Describe the bug**
When the renovate.json configuration file is invalid, the renovate Azure DevOps pipeline does not fail, but reports that everything went OK.

Maybe there is some configuration in the pipeline we are missing?

**To Reproduce**
1. Provide an incorrect renovate.json config file in your Git repository.
2. Run renovate Azure DevOps pipeline
3. Wait for the pipeline to be finished.

**Expected behavior**
The Azure DevOps Pipeline fails

**Screenshots**
![image](https://github.com/jycouet/VSTSExtensions/assets/8722437/08fd67f9-a44c-45c9-8a92-c1c5f5b2761a)

**Additional context**
Here is the logging output from the pipeline task: 
```
npm WARN
 exec The following package was not found and will be installed: renovate@37.218.0

...

 INFO: Repository has invalid config (repository=<your Azure DevOps git repository>)
       "error": {
         "validationSource": "renovate.json",
         "validationError": "Duplicate keys in JSON",
         "validationMessage": "\"Syntax error: duplicated keys \\\"prConcurrentLimit\\\" near imit\\\" : 10\"",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at checkForRepoConfigError (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/lib/workers/repository/init/merge.ts:213:17)\n    at mergeRenovateConfig (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/lib/workers/repository/init/merge.ts:237:3)\n    at getRepoConfig (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/lib/workers/repository/init/config.ts:12:12)\n    at initRepo (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/lib/workers/repository/init/index.ts:53:12)\n    at Object.renovateRepository (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/lib/workers/repository/index.ts:56:14)\n    at attributes.repository (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/lib/workers/global/index.ts:200:11)\n    at start (/home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/lib/workers/global/index.ts:185:7)\n    at /home/vsts/.npm/_npx/59c0475bfd22776c/node_modules/renovate/lib/renovate.ts:18:22"
       }

...

 INFO: Renovate was run at log level "info". Set LOG_LEVEL=debug in environment variables to see extended debug logs.
```

**Comment by jycouet** [comment]
👋 Hi, 
Thank you for reporting.

I'm wondering if we can catch this as in `renovate` it's just an `INFO:` as showed in the logs. 🤔

**Comment by KaVeKa** [comment]
Thanks for the quick response!

I was also surprised to see that this was logged as INFO and not as WARN or ERROR.

However, there is clearly a structured error response from somewhere inside the renovate process. I don't know if that is accessible from somewhere in your plugin code.

**Comment by jycouet** [comment]
Okay 👍

You can probably add this step in your `yaml` ? 👀

**Comment by KaVeKa** [comment]
I wouldn't know how? Can we directly call that config-validation command from the Azure DevOps pipeline?
I assume that it can more easily be ran from the index.ts file in your task?

**Comment by KaVeKa** [comment]
It took me a while to get back to, but I created a PR :)
I based myself on the renovate documentation: https://docs.renovatebot.com/config-validation/

**Comment by jycouet** [comment]
It doesn't build on my MAC.
I'll try thiw week on windows 🤞

**Comment by jycouet** [comment]
Should be in `1.0.3`. Let me know.
