### ISSUE TITLE
Version mismatch in config files

### ISSUE THREAD

**Issue by KaVeKa** [jycouet/VSTSExtensions#72]
**Describe the bug**
Versions in config files are not aligned

**To Reproduce**
Run RenovateMe Azure DevOps task which does not show the correct version

**Expected behavior**
The correct version is shown in the pipeline run logs.

**Screenshots**
Run with RenovateMe extension version 1.0.3
![image](https://github.com/jycouet/VSTSExtensions/assets/8722437/3123760d-0a9c-4f06-854b-35ea78f1f61c)

**Comment by KaVeKa** [comment]
@jycouet As requested, a new bugticket with a PR already attached. :)

**Comment by jycouet** [comment]
I'll go on my windows later ;)
Thx a lot

**Comment by KaVeKa** [comment]
@jycouet No pressure or urgency, just to be in the loop. When would you be able to merge and release this? :)

**Comment by jycouet** [comment]
Oups ! Will do tomorrow 🤞

**Comment by jycouet** [comment]
Omg ! Totally forgot... And now I'm 10days out. 😬

Sorry for the delay.

**Comment by jycouet** [comment]
I had to republish a `.4` to align things.
Let me know if it's ok now.

Sorry for the delay.
