### ISSUE TITLE
Add support for Node version 20

### ISSUE THREAD

**Issue by poldenburg** [jycouet/VSTSExtensions#79]
Renovate 38 requires node version 20.
Can you update the extension to support this node version?

**Comment by jycouet** [comment]
What is needed to support it ?

**Comment by poldenburg** [comment]
I'm not sure, maybe only update the node version, like in PR #69

**Comment by poldenburg** [comment]
@jycouet do you have time to look into this?

**Comment by jycouet** [comment]
I just released a version `1.0.6`, close the ticket if it's working :)

**Comment by poldenburg** [comment]
Great, thanks! The extension has been updated, but the pipeline still uses the old version (1.0.5), seems like a caching issue. I'll check again after the weekend.

**Comment by jycouet** [comment]
Would you like to do a PR ? :)

**Comment by jycouet** [comment]
Let's close this one with `1.0.8` ! :)
